# ------------------------------------------------------------------------------
# Github Workflow to commit to development branch ...
#
#   - This pipeline is triggered manually by developers at various times
#     
#     1) Run predefined tests for this project in wM.io DEV environment
#        - Calls workflow postman-validation to perform tests
#   
#     2) If validation successful: 
#        - Check out development branch 
#        - Run an export of all dev assets for this project in wM.io
#        - Perform a commit/push to git origin for this development branch
# 
# ------------------------------------------------------------------------------
name: Commit Development
run-name: Commit Development
on: [workflow_dispatch]

jobs:
  Dev-Validation:
    uses: HMHansson/ICA-DevOps/.github/workflows/validation-bruno.yml@main
    secrets: inherit
    with:
      environment: Development

  Commit:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [Dev-Validation]
    uses: HMHansson/ICA-DevOps/.github/workflows/commit-development.yml@main
    secrets: inherit
    with:
      environment: Development
  