# ------------------------------------------------------------------------------
# Github Workflow to validate functionality using Postman Collections
#
#  - This pipeline is triggered by
#     a) Manually start this workflow (from Github actions)
#     b) commit/push bruno test cases to development branch (using git client)
#
# ------------------------------------------------------------------------------
name: Dev Test Case Validation
run-name: Test Cases Validation
on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - 'test/TestCollection/**'

    
jobs:
  Run-Dev-Tests:
    uses: HMHansson/ICA-DevOps/.github/workflows/validation-bruno.yml@main
    with:
      environment: Development